[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }

[lib]
test = false
doctest = false

[[bin]]
name = "advent-of-code-2025"
path = "src/main.rs"
test = false

[[test]]
name = "runner"
harness = false
